### ISSUE TITLE
Sleep working?

### ISSUE THREAD

**Issue by kOOsi3** [jbwharris/hackintosh-msi-GL72M-7RDX#11]
Hi!

Wanted to know if you hackintosh's sleep function working 100%? Mine goes to sleep but wakes after few seconds. Screen stays off, but keyboard lights come back on and fans etc. I have read but so many stuff that can cause sleep to not function properly.

Regards
Cobus

**Comment by jbwharris** [comment]
It definitely does work for mine, though does seem a little idiosyncratic after the last macOS point update I did. It will deep sleep, but I have had a few times where it won't wake up lately and requires a hard restart.
