### ISSUE TITLE
Get stuck on the screen with the apple

### ISSUE THREAD

**Issue by FRJKNOEL** [jbwharris/hackintosh-msi-GL72M-7RDX#12]
Hello, I'm trying to install a hackintosh on my laptop and I'm having a lot of difficulties.
I tried your EFI folder but it doesn't work, I get stuck on a screen with the apple logo on it. I have a msi ge63 raider rgb 8rf. Do you have any idea why it doesn't work? Thank you

**Comment by FRJKNOEL** [comment]
I have restart with -v option and I have this error :
"In memory panic stackshot succeeded, Byte traced 12144"
"Attempting system restart...MACH Reboot"

**Comment by jbwharris** [comment]
Have you generated serials for your device? You can't just take my EFI and run it, as I've removed my serials from the config.plist.

**Comment by FRJKNOEL** [comment]
Okay that's probably because of that. I used another EFI folder and managed to install everything. I just have to see to install wifi, bluetooth and possibly make my gtx 1070 work.

**Comment by FRJKNOEL** [comment]
What kexts or drivers have you use to have the wifi ?

**Comment by jbwharris** [comment]
Have you replaced your Wifi card? I have a Broadcom wifi card that I swapped in, so not the stock MSI one.
