### ISSUE TITLE
I dont know to do hackintosh in msi GL72M-7RDX

### ISSUE THREAD

**Issue by rubenthis** [jbwharris/hackintosh-msi-GL72M-7RDX#14]
Hello, I have very little experience in this, I have been trying for a few months on my laptop but it does not work, I have an msi GL72M-7RDX and I don't know how to hackintosh, with your EFI folder what should I do, can you help me? Thank you

**Comment by jbwharris** [comment]
I'd think my EFI could get you 80% of the way there. In my repo I do have the settings in the bios you need, as well as the shortcut needed to unlock the advanced settings. If you have the stock Bluetooth/wifi card you'll need to swap that out if you want Airdrop/Sidecar etc. I'd recommend still doing the OpenCore guide, but I feel like I've ironed out the kinks in this build pretty well. I'm using Big Sur and it's working as well as it ever had and has had an uptime of a week so far without a reboot. It really works fantastic these days.

**Comment by harshsingh7** [comment]
Finally got my WebCam working, thank you for your support and your work and explanation for EFI etc is much appreciated...

The only thing bugging me now is That boot up without USB, Still not able to boot up my OpenCore without USB.
