### ISSUE TITLE
Discovering Various Internal Ports

### ISSUE THREAD

**Issue by harshsingh7** [jbwharris/hackintosh-msi-GL72M-7RDX#15]
Looking at your Project and Details, you have most of the stuff working. I have an MSI GE72VR-6RF Apache Pro laptop, the specs are almost identical, I have most some stuff working and some not, I want to know how did yo get the in-Built Camera detected and working and I m unable to boot without USB

**Comment by jbwharris** [comment]
I recall I used to have to almost bump start the camera. I'd open Photo Booth and have to press I believe Function(this may be FN or the Windows key, dependent on how you set it in the BIOS) + F6. On my keyboard there is a little webcam icon on there. That should turn on the camera. I believe there's some software level on / off for the camera, so unless you do that, it won't work. I believe I had a note about that back in my old [Clover Readme](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX/tree/master/Old%20Builds/Clover). 

As for booting there's a note at the bottom of that Clover build about how to setup the Boot Entries in Windows. If I'm guessing as to why it won't boot from the EFI of the drive you want, it's that the Boot Entries have become messed up at some point and the BIOS isn't pointed to pick your OpenCore drive as the first drive to try to boot with.

**Comment by harshsingh7** [comment]
I tried doing the photoBooth method but nothing seems to be working, tried with both Fn/Win key. It doesn't even show up in System Report. 

How do you point the bios to the correct partition, couldn't find it in openCore Docs.

**Comment by jbwharris** [comment]
Have you mapped your USB ports? I have mine in the kexts folder if you want to give it a shot. Could be that the camera isn't mapped properly.

**Comment by harshsingh7** [comment]
I'll give your USBMap a shot right now.

Also, I don't have Windows Installed. right now, so won't be able to figure out boot stuff

**Comment by jbwharris** [comment]
I'd recommend Hackintool for that, their explanation in the app explains the steps.

**Comment by harshsingh7** [comment]
Finally got my WebCam working, thank you for your support and your work and explanation for EFI etc is much appreciated...

The only thing bugging me now is That boot up without USB, Still not able to boot up my OpenCore without USB.

**Comment by jbwharris** [comment]
I'm still on 11.1, haven't run that update yet since my machine has been running pretty flawlessly, so didn't want to rock the boat if I didn't need to.
