### ISSUE TITLE
Steps Plz

### ISSUE THREAD

**Issue by didiosn** [jbwharris/hackintosh-msi-GL72M-7RDX#17]
Hi, I have the exact model of MSI, and I really want to hackintosh it !! 

Please can you provide me a step by step process to do it. 

Thank you.

**Comment by rlindsberg** [comment]
https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/

**Comment by jbwharris** [comment]
@didiosn This is really the only guide you should be using these days, the [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/). You can use my build to fill in some of the knowledge gaps you might have on the laptop, but it really is best to learn how to go about the whole process.

**Comment by didiosn** [comment]
Hi, I did follow the Guide, but my after format and install files, it needs to restart and continue the installation but it keeps rebooting on the apple. 
I saw that its a common issue but I just dont know what I did wrong or what to do.

Thanks

**Comment by didiosn** [comment]
I also try from scratch the OpenCore Guide for kabylake but no success. It doesn't even boot to install, I get stuck on DSMOS has arrived... Pfff. I really hope that the fact that we have the same computer will help... no luck

**Comment by didiosn** [comment]
Hello again, i managed to install it, but to make it work i've removed you ACPI file that concern your wifi adapter, and remove some args in boot. I have no sound and of course no wifi. it's better than before. 
If you have an idea to fix my audio problem, i'll be grateful.

**Comment by jbwharris** [comment]
You'll definitely need to swap out the wifi card, so it makes sense that needed to be removed. I know the audio is 98, I believe I had it defined in devices and as a bootarg.

**Comment by didiosn** [comment]
Alright, I'll handle the wifi card later. The sound is fix too. 

Thank you for your patience.
