### ISSUE TITLE
MSI is not booting anymore 

### ISSUE THREAD

**Issue by didiosn** [jbwharris/hackintosh-msi-GL72M-7RDX#18]
Hello, few days after successfull installation, suddenly, the computer do not want to boot from any device anymore. I've try an key with only EFI partition, still no luck, then full bootable BigSur install stick, still no luck.

Help me please.

**Comment by didiosn** [comment]
Hello, I found the issue, the computer was out of battery, so that re init the bios configuration. Is that a way to save the bios config as default ?

**Comment by rlindsberg** [comment]
> Hello, I found the issue, the computer was out of battery, so that re init the bios configuration. Is that a way to save the bios config as default ?

There is an option and I tried multiple times. It didn't work for me.

**Comment by jbwharris** [comment]
Try using the process in my old Clover guide [fixing boot issues](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX/blob/master/Old%20Builds/Clover/README.md) at the bottom of the README. Requires Windows to do.
