### ISSUE TITLE
Is there can use on GP72VR?

### ISSUE THREAD

**Issue by mattl1222** [jbwharris/hackintosh-msi-GL72M-7RDX#19]
Hi ,
I am a newbie on Hackintosh and I can't find the efi on GP72VR ,can this efi use on my laptop?

**Comment by kOOsi3** [comment]
Hi! It is best to build your own efi for your system from scratch. It is not that difficult. There should be a very detailed guide online.

https://dortania.github.io/OpenCore-Install-Guide/

I would suggest opencore.

Good luck
Cobus
