### ISSUE TITLE
Did you get HDMI Audio?

### ISSUE THREAD

**Issue by effeci** [jbwharris/hackintosh-msi-GL72M-7RDX#2]
As title says...

**Comment by jbwharris** [comment]
I just tested this yesterday and no, I didn't get that working. I'll have to add it to my bug list.

**Comment by effeci** [comment]
I have same problem on same platform

**Comment by jbwharris** [comment]
So you have GL72M 7RDX? Where are you on your build? I haven't encountered any people with this laptop, so I'd definitely be curious to see you you've figured anything out I still haven't.

**Comment by effeci** [comment]
Same platform means same CPU igpu. 
I have a t470p . Only miniDP audio is not working

**Comment by jbwharris** [comment]
I'd be interested in seeing your build if you'd be willing to share. I haven't had any luck with the display port at all.

**Comment by effeci** [comment]
You have to spoof graphics to skylake

**Comment by jbwharris** [comment]
Is that just as simple as including [this SSDT](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-SKLSPF.dsl)?

**Comment by effeci** [comment]
No it is trough config plist.... Details : https://www.tonymacx86.com/threads/readme-common-problems-and-workarounds-on-10-14-mojave.255823/

**Comment by jbwharris** [comment]
Gave that a try and it definitely messed things up. Lost all my screen brightness controls.

**Comment by effeci** [comment]
Weird..... I guess it depends on how it was implemented. What did you do exactly? BTW today I had audio on miniDp working with kaby lake IDs.... But it lasted 1 reboot

**Comment by jbwharris** [comment]
I actually spoke too soon. Turns out I'd mistyped the values in the first time around. Display port now works for the first time. Now I just have the problem that I can't actually use HDMI and DP at the same time because my HDMI to DVI adapter won't fit simultaneously. Now I just need to test audio. Thanks for the help, didn't actually expect to get DP working.

**Comment by effeci** [comment]
Let me know about audio

**Comment by jbwharris** [comment]
No luck on the audio so far. I have no way of testing the display port audio at this point as I don't have the right adapter to even attempt it. I was able to cobble together a way of testing DP and HDMI at the same time last night, which worked pretty well.

**Comment by effeci** [comment]
HDMI and miniDp should have audio on the same bus... I got audio working ... But it corrupts upon waking from sleep. Let me see your efi folder if you don't mind

**Comment by jbwharris** [comment]
I'll upload it to Github tonight, meant to last night but it didn't happen.

**Comment by effeci** [comment]
What else is not working on yours?

**Comment by jbwharris** [comment]
The list is actually getting quite small. I was mucking around a bit with trying to get the SD card reader working yesterday. The Bluetooth is a little unstable when connecting to my BT speakers. I'm also not sure if I have the battery implemented properly. It obviously does work, but I'm not sure if there's work to be done there. And there's also the GTX 1050 if they ever release Mojave drivers. I've never been quite sure what the deal is with that as when my laptop wakes up from it's first sleep after a reboot the power light is red instead of blue, which I believe indicates it's running off the GTX 1050.

**Comment by effeci** [comment]
GTX 1050 should be disabled if Optimus connected. It is done through ssdt. Led after sleep the same trought ssdt. What wifi do you have ( that's what I miss) and are u in Europe I guess right?

**Comment by effeci** [comment]
Sdcard is a lost cause more or less...

**Comment by jbwharris** [comment]
GTX 1050 is disabled, but I was never sure if it was working in spite of the being disabled given the LED changes colour. I have a DW1820A BCM94350ZAE that I swapped into the laptop. The Bluetooth had been one of my most troublesome issues and I only just got it working a week or two ago. SD Card is kinda irrelevant, but I tried all the same in an effort to get 100% functionality. From the articles I encountered, people seemed to be having issues with Mojave in particular and the methods that worked previously seem to be broken. I'm in Canada actually.

**Comment by effeci** [comment]
Can't find so much wifi compatible cards here in Europe. BTW getting mad to enable HDMI audio

Il 20 feb 2019 19:51, James Harris <notifications@github.com> ha scritto:

GTX 1050 is disabled, but I was never sure if it was working in spite of the being disabled given the LED changes colour. I have a DW1820A BCM94350ZAE that I swapped into the laptop. The Bluetooth had been one of my most troublesome issues and I only just got it working a week or two ago. SD Card is kinda irrelevant, but I tried all the same in an effort to get 100% functionality. From the articles I encountered, people seemed to be having issues with Mojave in particular and the methods that worked previously seem to be broken. I'm in Canada actually.

**Comment by jbwharris** [comment]
Here's my EFI folder https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX/tree/master/EFI%20folders/EFI-Mojave-10.14.2

**Comment by effeci** [comment]
I'll take a look, thanks. Let me know if you have HDMI or miniDp audio with these settings.

**Comment by effeci** [comment]
Solved the audio trought HDMI....
https://www.tonymacx86.com/threads/minidp-audio-not-working-kabylake-14-3-hd630.272048/
Take a look to the last post

**Comment by jbwharris** [comment]
I had no luck trying that edit, just undid many of my screen features like brightness and HDMI/DP out. Could I see your config.plist to compare?

**Comment by effeci** [comment]
Go into my profile, there's another topic .. open the last attached debug. If you can't find it I'll post it tomorrow.

**Comment by jbwharris** [comment]
I didn't end up finding it
