### ISSUE TITLE
How can make usb-typeC work?

### ISSUE THREAD

**Issue by CHN-STUDENT** [jbwharris/hackintosh-msi-GL72M-7RDX#21]
Hi,
I am Chinese hackintosher using GP62-6QG-1281XCN(15.6in,i5-6300HQ,965M,16G,960EVO 500G) , i use yours and [chuxubanks](https://github.com/chuxubank/MSI-GP62-Hackintosh) opencore config to make my opencore. Now I can use big sur 12.6 by using opencore 0.7.4. But there are same issue need me to fix.

- Would you open system, you build-in speaker will broke once?
- The usb-TypeC can not work @chuxubanks and my laptop, how can you find this path? I found it in windows (hs01/hs02;ss01,ss02) but not work. Could you give me some advice?
- also chuxubanks and my laptop can not sleep and wake up, i hope you can give me advice too.
- I see a unoffical reader driver https://github.com/0xFireWolf/RealtekCardReader , i think i will try if i am free.

**Comment by rlindsberg** [comment]
Have to tried patching USB ports with Hackintool?

**Comment by CHN-STUDENT** [comment]
ok , i will try if i am going home again. But  I remember any Usb-type device can not display in hackintool, so how can you do?

**Comment by CHN-STUDENT** [comment]
@rlindsberg @jbwharris Thanks! At last, i try to fixUSB mapping again in hackintool, and i found i need to load `usbports.kext` instead of `ssdt-uiac.kext` and `usbinjecall.kext`, i do not why second way  is not work, but i can use typeC now! Thank you!
My typec  USB mapping is HS01,HS02,SS01,SS02

And i still try to fix other issue? Do you have any suggest to make me fix wake-up issue? Thanks! And i want to know if you open system,your build-in speaker will broke once?

**Comment by rlindsberg** [comment]
Glad that we could help!
BTW, if you are using Catalina 10.15.4 and later, be aware of the fact that sleep/wake may be broken (due to Apple's bug). So by a small chance, you will get kernel panic after waking up the computer. Disable sleep to be safe.
