### ISSUE TITLE
Add SDCARD Driver Please

### ISSUE THREAD

**Issue by CHN-STUDENT** [jbwharris/hackintosh-msi-GL72M-7RDX#22]
see here: https://github.com/0xFireWolf/RealtekCardReader
My GP62 is RTS5129
It works on HS12
May someone will use it.

![image](https://user-images.githubusercontent.com/21209416/138127591-bbd6049e-e77f-4163-bf08-0d659302414c.png)

**Comment by rlindsberg** [comment]
Awesome! Thanks for sharing!
