### ISSUE TITLE
Framebuffer & external display support

### ISSUE THREAD

**Issue by PeuTit** [jbwharris/hackintosh-msi-GL72M-7RDX#24]
Hello,

I'm trying to use my HDMI & Displayport with my Hackintosh build. I don't have quite the same laptop as you but I do have the same iGpu, an intel graphics 630. My laptop model is the MSI gl63 8re. 

I wondered if you could give me any input on how you made it work with your build.

Thanks!

**Comment by rlindsberg** [comment]
HDMI: https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/#terminology
DP will not work.

**Comment by jbwharris** [comment]
@rlindsberg It actually does work with my build. I can't I'm super on top of the why side of things, but I just tested that it does still work. I switched to just using a single big monitor instead of 2 external monitors, but this laptop will drive 2 external monitors on HDMI and Mini DP.

**Comment by rlindsberg** [comment]
> @rlindsberg It actually does work with my build. I can't I'm super on top of the why side of things, but I just tested that it does still work. I switched to just using a single big monitor instead of 2 external monitors, but this laptop will drive 2 external monitors on HDMI and Mini DP.

That's nice! For me it gives me kernel panic as soon as I plug in miniDP. So I couldn't patch it...

**Comment by rlindsberg** [comment]
> I believe my ports are routed through the dGPU. Does that change a thing or not?
> 
> I've tested to deactivate the dGPU in the bios and was not able to get display output on Windows.

In a hackintosh you cannot have both iGPU and dGPU working. So if you choose dGPU you have to disable iGPU in BIOS. Then you probably lose internal display but you have DP output. Otherwise no DP.

**Comment by PeuTit** [comment]
Hum ok but I can't use my Nvidia GPU with latest version of Mac OS right? So I'm stuck with just my internal display.

**Comment by PeuTit** [comment]
> > Hum ok but I can't use my Nvidia GPU with latest version of Mac OS right? So I'm stuck with just my internal display.
> 
> GTX 100 series work up to High Sierra. RTX 2000 and newer do not work on any macOS. You may read more here: https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/nvidia-gpu.html#kepler-series-gtx-6xx-7xx

Ah damn I think I can give up on external display support.

Thank you for taking the time to help me, really appreciate it!

**Comment by rlindsberg** [comment]
> Ah damn I think I can give up on external display support.
> 
> Thank you for taking the time to help me, really appreciate it!

You are welcome!

I currently have the following specs, basically same as you. I am able to edit 4k 24 fps videos in Final Cut Pro without dropping frames. And NVIDIA drivers are buggy on macOS. So I'm very happy that I have iGPU only.

![Skærmbillede 2022-02-14 kl  19 33 03](https://user-images.githubusercontent.com/2918707/153924960-db7e4c94-831e-4a9a-a043-324b5f0d6433.png)

**Comment by jbwharris** [comment]
I definitely have my setup with the Nvidia card disabled in Big Sur. I use my laptop as my daily driver without much issue. I do web development and graphic design work, but rarely, if ever, video rendering.

**Comment by PeuTit** [comment]
The only thing that prevents me from using the laptop full time si the external display support! Apart from that, Mac OS works exceptionally great.

**Comment by rlindsberg** [comment]
> The only thing that prevents me from using the laptop full time si the external display support! Apart from that, Mac OS works exceptionally great.

If you have bought a 1050 Ti or lower GPU, the DP is routed through iGPU. Then you could have two external monitors working! Have you tried USB3.1 Gen2 to HDMI adapter? It would lag a little bit, but works if you are not watching videos or gaming.
