### ISSUE TITLE
How you got the 1050 working?

### ISSUE THREAD

**Issue by dragoniil1** [jbwharris/hackintosh-msi-GL72M-7RDX#3]
I have a GS63 7RE STEALTH PRO with a broadcom wifi replacement on the way, after it arrives i will try to get macos on my laptop but untill then i have 1 question. 
As far as i know laptops with nvidia gpus have optimus and this tehnology is not supported on mac os, how did you got that working?

**Comment by jbwharris** [comment]
It only works in High Sierra, since there were actually nvidia drivers for that OS. They haven't released new ones for Mojave. I can't say I've mucked with it in quite awhile, personally I prefer dark mode over having the 1050 fully functional.

**Comment by dragoniil1** [comment]
> That's awesome @dragoniil1 !
> 
> I would like to see how Mac runs on GS-series. I might can help you with installing and debugging!

i managed to install it and run it a few times but my limited knowledge aboutthis topic set me back, the few times i managed to install it even managed to get the igpu working i screwed it up somehow when i started to configure things and failed to boot after, and as far as i know i dont have a way to revert the changes and try again wtihout reinstalling mac os, my main goal was to have mac os on an external ssd and when it is plugged the laptop will boot into it, when is not the laptop will boot into windows, this part worked and i noticed that mac os drained a lot of battery and i wanted to install kexts to fix that and here is the point where i gave up, without internet on my macos made things so much harder and took so much time to keep restarting the computer just to put some files on a usb stick, that's why im waiting to replace the wifi card, i will get back here after i will install it

**Comment by rlindsberg** [comment]
> i screwed it up somehow when i started to configure things and failed to boot after

You should use Git, which is why me and @jbwharris are here. I have been working with hackintosh since Mac OS X 10.7 Lion. There is one single thing I learned from my mistakes is that you gotta document everything you do, and use Git.



> my main goal was to have mac os on an external ssd and when it is plugged the laptop will boot into it, when is not the laptop will boot into windows

That is interesting. I installed Mac and windows on an _internal_ _**single**_ SSD. I can choose which os I want to boot.




> without internet..

Errr, AtherosE2200Ethernet.kext can drive your ethernet card!

**Comment by dragoniil1** [comment]
i dont quite know how to use git, never used it, and about the internet on one of the installs i got my phone to share the wifi via usb to mac but aparently it was a one time thing didnt manage to make it work again, and the AtherosE2200Ethernet.kext is just for wired internet and i dont have a long anough cable to bring it to my laptop, and about the usb wifi dongle thing i said in the long run i have to take it with me so is better just to buy a replacement m.2 card, also a 1 time thing was the bluetooth got it working somehow when i tried to share internet from my phone managed to share it via bluetooth, and the laptop has a killer wifi m.2 card hackintosh is so unpredictable sometimes

**Comment by dragoniil1** [comment]
and also if there is a proper way to discuss those things, i have a few more questions but i dont feel like this is the proper location to discuss them via email maybe, or does github has private massages?

**Comment by rlindsberg** [comment]
Github is for discussing about _code issues_ and _pull requests_. It is not intended for asking questions; I would recommend you to ask on https://www.tonymacx86.com

However, I suggest never defend for something because that will make people just go away. For example: 

> i dont quite know how to use git, never used it

**Comment by bizzyman** [comment]
I also am wondering about the original title of this issue? 
Is this laptup muxed? I.e. are the video out ports routed to the graphics card? Can you switch to discrete only graphics in the bios? Because if you did get the 1050 working and it it is optimus based, that would be a breakthrough for hackintoshing.

**Comment by jbwharris** [comment]
@bizzaman I can't say with 100% certainty, but I believe I was using the nvidia card with that setup. There's a light on my laptop that indicated whether I'm using the IGPU or the GPU. I was able to install the nvidia web drivers and they did work, but I had a whole bunch of other issues, so I just doubled back to using my IGPU and never really looked back.

**Comment by sxzz** [comment]
However, when using a 4K monitor and turning on HiDPi, using Intel graphics cannot display some animation smoothly. It seems that Intel graphics cannot render 5K resolution. Is it caused by insufficient graphics memory? I have no idea.

> Resolution:	5120 x 2880 (5K/UHD+ - Ultra High Definition Plus)
  UI Looks like:	2560 x 1440 @ 60 Hz

**Comment by jbwharris** [comment]
I haven't mucked with the 1050 in ages, but a suggestion I'd have is maybe changing to 64M of DVMT Pre-Allocated memory in the BIOS. Check out my [OpenCore BIOS section](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX/tree/master/OpenCore) for instructions on how to change that.

**Comment by sxzz** [comment]
@jbwharris I've modified this option, but it still doesn't work. Well, thank you anyway.

**Comment by jbwharris** [comment]
@sxzz It took a little bit to get this working for me. You have to take out any patches, I found the [OC laptop guide](https://dortania.github.io/oc-laptop-guide/prepare-install-macos/display-configuration.html) quite useful explaining this part exactly.

![image](https://user-images.githubusercontent.com/2962327/82382639-4fec9580-99fa-11ea-9856-aa185a0b9ccd.png)

**Comment by sxzz** [comment]
Well, actually I tried this patch too. But, this will cause hidpi to fail to enable

**Comment by vjkrvkarma** [comment]
Hi @jbwharris 
Did you get full acceleration of Nvidia 1050?
In my case, it is showing Nvidia Chip Model with 0mb VRAM.
![IMG20200630130359](https://user-images.githubusercontent.com/36467462/86202117-03f74980-bb7f-11ea-9e44-84b00ea89c37.jpg)

**Comment by rlindsberg** [comment]
> @bizzaman I can't say with 100% certainty, but I believe I was using the nvidia card with that setup. There's a light on my laptop that indicated whether I'm using the IGPU or the GPU. I was able to install the nvidia web drivers and they did work, but I had a whole bunch of other issues, so I just doubled back to using my IGPU and never really looked back.

@vjkrvkarma 


Now I read the whole thread again and saw that you mentioned the light indicator.

Well, it turns red when the DGPU is activated, but it does not mean that it is properly working in Mac. The reason why is that Mac never support multiple GPUs. If intel GPUs is driving your screen as shown below, then DGPU won't work.

![Screen Shot 2020-07-01 at 5 14 50 PM](https://user-images.githubusercontent.com/2918707/86261069-615ebb00-bbbe-11ea-812d-247691cc60d8.png)
