### ISSUE TITLE
Does wifi work out OOTB

### ISSUE THREAD

**Issue by cristianpardoo** [jbwharris/hackintosh-msi-GL72M-7RDX#4]
Hi, I have the same wifi card and am about to install. Which drivers other than the bluetooth ones do i need to get it working? Thanks for reading.

**Comment by jbwharris** [comment]
It's been awhile since I've done this, but I recall it being a little finicky to get the Bluetooth working. If I recall correctly I had to turn off SIP when installing them, then re-enable it afterwards.
