### ISSUE TITLE
access the "Advanced BIOS"

### ISSUE THREAD

**Issue by xin10355** [jbwharris/hackintosh-msi-GL72M-7RDX#6]
for GL62M-7RDX-1286CN
To access the "Advanced BIOS" enter the BIOS and press CTRL and SHIFT right and ALT and F2 left

**Comment by jbwharris** [comment]
Thanks for this, definitely useful info and I'll add as a tip to my build

**Comment by jbwharris** [comment]
@xin10355 Do you have a functioning EFI for your machine? If so I'd love to take a look.

**Comment by ForceGT** [comment]
+1 I have the same model would love to have a look at your EFI
