### ISSUE TITLE
Catalina audio doesn't work

### ISSUE THREAD

**Issue by nathanielc-lab** [jbwharris/hackintosh-msi-GL72M-7RDX#8]
Hello, Audio for internal speakers does not seem to be detected in Catalina,

Thanks

**Comment by jbwharris** [comment]
I know my audio has always needed to be set to 98 in the boot args.

**Comment by nathanielc-lab** [comment]
Hi, I can't see anywhere in bootargs which say about audio and can be set to 98, thanks

**Comment by jbwharris** [comment]
it's  alcid=98 in the boot args

I also have this set under DeviceProperties
![image](https://user-images.githubusercontent.com/2962327/88499523-17d27780-cf94-11ea-8fb7-d7b132d75992.png)

**Comment by nathanielc-lab** [comment]
I was looking at sounds and it says realtek 889, could this be the issue as your GL62M 7rdx is 889?  If so do you know how I could possibly fix this? Thanks

**Comment by jbwharris** [comment]
Mine is ALC889 as well. I don't believe those values correspond with the model number.

**Comment by nathanielc-lab** [comment]
Alright, could I possibly send over my clover files to you and you have a look? As this problem is driving me up the wall lol

**Comment by jbwharris** [comment]
Sure, I can take a look
